#!/bin/sh -

sed -e 's/^\(.*\)#.*$/\1/' -e '/^[[:space:]]*$/d' "$1" | \
    awk 'BEGIN{
             FS = "=";
             printf "reject=";
         }
         {
             if ( NR != 1 ) {
                    printf ",\n";
                 }
             printf "\"%s\"", $2;
         }
         END {
                 print ";";
         }'
